"""team and player stats tables

Revision ID: V20220809T2156
Revises: V20220803T2143
Create Date: 2022-08-09 22:01:51.418134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "V20220809T2156"
down_revision = "V20220803T2143"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_stats",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("acs", sa.Integer(), nullable=False),
        sa.Column("adr", sa.Integer(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("first_bloods", sa.Integer(), nullable=False),
        sa.Column("first_deaths", sa.Integer(), nullable=False),
        sa.Column("kast", sa.Float(), nullable=False),
        sa.Column("hsp", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("game_id", "team_id", "player_id"),
        schema="dp_valorant",
    )
    op.create_table(
        "team_stats",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("defense_score", sa.Integer(), nullable=False),
        sa.Column("attack_score", sa.Integer(), nullable=False),
        sa.Column("attack_start", sa.Boolean(), nullable=False),
        sa.Column("map_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("match_id", "game_id", "team_id"),
        schema="dp_valorant",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_stats", schema="dp_valorant")
    op.drop_table("player_stats", schema="dp_valorant")
    # ### end Alembic commands ###
